### Device type (COMPUTER, TABLET, SMARTPHONE, SPEAKER, TV, AVR, STB, AUDIO_DONGLE, GAME_CONSOLE, CAST_VIDEO, CAST_AUDIO, AUTOMOBILE, WEARABLE, UNKNOWN_SPOTIFY, CAR_THING, UNKNOWN) ###
deviceType = "SPEAKER"
### Device name ###
deviceName = "qtplayer"
### Device ID (40 chars, leave empty for random)  ###
deviceId = ""
### Log level (OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL) ###
logLevel = "TRACE"
### Preferred locale ###
preferredLocale = "en"

### Cache ###
[cache]
	dir = "./cache/"
	# Cache enabled
	enabled = true
	doCleanUp = true

### Authentication ###
[auth]
	# Credentials file (JSON)
	credentialsFile = ""
	# Spotify password (USER_PASS only)
	password = ""
	# Spotify authentication blob (BLOB only)
	blob = ""
	# Whether to store reusable credentials on disk (not a plain password)
	storeCredentials = false
	# Strategy (USER_PASS, ZEROCONF, BLOB, FACEBOOK)
	strategy = "ZEROCONF"
	# Spotify username (BLOB, USER_PASS only)
	username = ""

### Preload ###
[preload]
	# Preload enabled
	enabled = true

### Proxy ###
[proxy]
	# Basic auth password
	password = ""
	# The proxy hostname
	address = ""
	# The proxy port
	port = 0
	# Whether authentication is enabled on the server
	auth = false
	# The proxy type (HTTP, SOCKS)
	type = "HTTP"
	# Whether the proxy is enabled
	enabled = false
	# Basic auth username
	username = ""

### Zeroconf ###
[zeroconf]
	# Listen on all interfaces (overrides `zeroconf.interfaces`)
	listenAll = true
	# Listen on these interfaces (comma separated list of names)
	interfaces = ""
	# Listen on this TCP port (`-1` for random)
	listenPort = -1

### Time correction ###
[time]
	# Manual time correction in millis
	manualCorrection = 0
	# Time synchronization method (NTP, PING, MELODY, MANUAL)
	synchronizationMethod = "NTP"

### API ###
[api]
	# API port (`api` module only)
	port = 24879
	# API listen interface (`api` module only)
	host = "0.0.0.0"

### Player ###
[player]
	# Whether to apply the Spotify loudness normalisation
	enableNormalisation = false
	# Initial volume (0-65536)
	initialVolume = 65536
	# Release mixer line after set delay (in seconds)
	releaseLineDelay = 20
	# Normalisation pregain in decibels (loud at +6, normal at +3, quiet at -5)
	normalisationPregain = 0.0
	# Output metadata in Shairport Sync format (https://github.com/mikebrady/shairport-sync-metadata-reader)
	metadataPipe = ""
	# Autoplay similar songs when your music ends
	autoplayEnabled = true
	# Preferred audio quality (NORMAL, HIGH, VERY_HIGH)
	preferredAudioQuality = "VORBIS_320"
	# Audio output device (MIXER, PIPE, STDOUT)
	output = "MIXER"
	# Whether the playback should be stopped when the current chunk cannot be downloaded
	stopPlaybackOnChunkError = false
	# Crossfade overlap time (in milliseconds)
	crossfadeDuration = 0
	# Mixer/backend search keywords (semicolon separated)
	mixerSearchKeywords = ""
	# Output raw (signed) PCM to this file (`player.output` must be PIPE)
	pipe = ""
	# Log available mixers
	logAvailableMixers = true
	# Number of volume notches
	volumeSteps = 64
